"""Create project-local Codex MCP config without overwriting existing settings."""
from __future__ import annotations

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def main() -> None:
    runtime = Path(__file__).parent / ".venv" / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    if not runtime.is_file():
        raise SystemExit("First run: uv sync --project tools/agent_hub --locked")
    config = ROOT / ".codex/config.toml"
    if config.exists():
        raise SystemExit("Project config already exists; merge the MCP entry manually to preserve existing settings.")
    config.parent.mkdir(exist_ok=True)
    quote = lambda path: json.dumps(str(path.resolve()).replace("\\", "/"))
    content = (
        "# Machine-local file generated by tools/agent_hub/configure_codex.py\n"
        "[mcp_servers.rl_agent_hub]\n"
        f"command = {quote(runtime)}\n"
        f"args = [{quote(Path(__file__).with_name('server.py'))}]\n"
        f"cwd = {quote(ROOT)}\n"
        "startup_timeout_sec = 20\n"
        "tool_timeout_sec = 30\n"
        "[mcp_servers.rl_agent_hub.env]\n"
        f"RL_AGENT_HUB_DB = {quote(ROOT / '.agent-state/hub.sqlite3')}\n"
    )
    with config.open("x", encoding="utf-8") as output:
        output.write(content)
    print(f"Configured {config}; load the project in a new trusted Codex session.")


if __name__ == "__main__":
    main()
